version: '3.8'

services:
  n8n-lab:
    image: agus33ina/n8n-lab:v1
    container_name: n8n-lab
    ports:
      - "5678:5678"
    restart: always
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
